In [8]:
import pandas as pd
import os

In [9]:
## Series
lst1 = [1,2,3,4,5,6,7,8,9]
series = pd.Series(lst1)
series

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [10]:
data = {
    "Name" : ['Navneet', "Manish", "Devendra"],
    "Age" : [25,25,25]
}

dataframe = pd.DataFrame(data)
dataframe

       Name  Age
0   Navneet   25
1    Manish   25
2  Devendra   25

In [11]:
os.getcwd()

'c:\\Users\\Syed\\Desktop\\ADV Py'

In [12]:
## Importing Dataset
df = pd.read_csv('data\covid_toy.csv')
df.head()

<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:2: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Syed\AppData\Local\Temp\ipykernel_9024\1304322875.py:2: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv('data\covid_toy.csv')

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [13]:
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    str
 2   fever      90 non-null     float64
 3   cough      100 non-null    str
 4   city       100 non-null    str
 5   has_covid  100 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 4.8 KB

In [15]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [16]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
## .loc and .iloc
df.loc[5:10, ['age', 'fever']]

    age  fever
0    60  103.0
1    27  100.0
2    42  101.0
3    31   98.0
4    65  101.0
..  ...    ...
95   12  104.0
96   51  101.0
97   20  101.0
98    5   98.0
99   10   98.0

[100 rows x 2 columns]

In [18]:
df.iloc[10:15, 0:2]

    age  gender
10   75  Female
11   65  Female
12   25  Female
13   64    Male
14   51    Male

In [21]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [22]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='str')

In [23]:
## Filling the missing vaues
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [27]:
df = pd.read_csv('data\covid_toy.csv')

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Syed\AppData\Local\Temp\ipykernel_9024\3918093160.py:1: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv('data\covid_toy.csv')

In [28]:
fever_mean = df['fever'].mean()
df.fillna(fever_mean, inplace=False)

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [29]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [30]:
df['fever'] = df['fever'].fillna(df['fever'].mean())
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [31]:
## Dropping the missing values
df = pd.read_csv('data\covid_toy.csv')

df = df.dropna()
df.info()

<class 'pandas.DataFrame'>
Index: 90 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        90 non-null     int64
 1   gender     90 non-null     str
 2   fever      90 non-null     float64
 3   cough      90 non-null     str
 4   city       90 non-null     str
 5   has_covid  90 non-null     str
dtypes: float64(1), int64(1), str(4)
memory usage: 4.9 KB

<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:2: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Syed\AppData\Local\Temp\ipykernel_9024\677643796.py:2: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv('data\covid_toy.csv')

In [32]:
## Dropping a specific column
df = pd.read_csv('data\covid_toy.csv')

df = df.drop(columns= ['has_covid'])
df.head()

<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:2: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Syed\AppData\Local\Temp\ipykernel_9024\876027697.py:2: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv('data\covid_toy.csv')

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai

In [37]:
df = pd.read_csv('data\covid_toy.csv')

x = df.drop(columns= ['has_covid', 'age'])
y = df['has_covid']

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Syed\AppData\Local\Temp\ipykernel_9024\3373351582.py:1: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv('data\covid_toy.csv')

In [38]:
x

    gender  fever   cough       city
0     Male  103.0    Mild    Kolkata
1     Male  100.0    Mild      Delhi
2     Male  101.0    Mild      Delhi
3   Female   98.0    Mild    Kolkata
4   Female  101.0    Mild     Mumbai
..     ...    ...     ...        ...
95  Female  104.0    Mild  Bangalore
96  Female  101.0  Strong    Kolkata
97  Female  101.0    Mild  Bangalore
98  Female   98.0  Strong     Mumbai
99  Female   98.0  Strong    Kolkata

[100 rows x 4 columns]

In [35]:
y

0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: str

In [ ]:
df = pd.read_csv('data\covid_toy.csv')

df = df.rename(columns= {"has_covid" : "isCovid"})
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Syed\AppData\Local\Temp\ipykernel_9024\2137849465.py:1: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv('data\covid_toy.csv')

   age  gender  fever cough     city isCovid
0   60    Male  103.0  Mild  Kolkata      No
1   27    Male  100.0  Mild    Delhi     Yes
2   42    Male  101.0  Mild    Delhi      No
3   31  Female   98.0  Mild  Kolkata      No
4   65  Female  101.0  Mild   Mumbai      No

In [40]:
df['Age'] = df['age'] + 10
df.head()

   age  gender  fever cough     city isCovid  Age
0   60    Male  103.0  Mild  Kolkata      No   70
1   27    Male  100.0  Mild    Delhi     Yes   37
2   42    Male  101.0  Mild    Delhi      No   52
3   31  Female   98.0  Mild  Kolkata      No   41
4   65  Female  101.0  Mild   Mumbai      No   75

In [42]:
df[['age', 'city']].head()

   age     city
0   60  Kolkata
1   27    Delhi
2   42    Delhi
3   31  Kolkata
4   65   Mumbai

In [46]:
df.sample(10)

    age  gender  fever   cough       city isCovid  Age
28   16    Male  104.0    Mild    Kolkata      No   26
88    5  Female  100.0    Mild    Kolkata      No   15
17   40  Female   98.0  Strong      Delhi      No   50
90   59  Female   99.0  Strong      Delhi      No   69
33   26  Female   98.0    Mild    Kolkata      No   36
76   80    Male  100.0    Mild  Bangalore     Yes   90
98    5  Female   98.0  Strong     Mumbai      No   15
60   24  Female  102.0  Strong  Bangalore     Yes   34
7    20  Female    NaN  Strong     Mumbai     Yes   30
0    60    Male  103.0    Mild    Kolkata      No   70