In [1]:
import pandas as pd
import os

In [ ]:
## Series
lst1 = [1,2,3,4,5,6,7,8,9]
series = pd.Series(lst1)
series

lst2 = [2,4,6,8,10]
series = pd.Series(lst2)
series

#  Series is used to return array from dataframe

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [7]:
df = pd.read_csv("data\covid_toy.csv")

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Syed\AppData\Local\Temp\ipykernel_3656\2614522238.py:1: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv("data\covid_toy.csv")

In [ ]:

series = pd.Series(df["age",])
series

0     60
1     27
2     42
3     31
4     65
      ..
95    12
96    51
97    20
98     5
99    10
Name: age, Length: 100, dtype: int64

In [ ]:
data = {
    "Name" : ['Navneet', "Manish", "Devendra"],
    "Age" : [25,25,25]
}

dataframe = pd.DataFrame(data)
dataframe

       Name  Age
0   Navneet   25
1    Manish   25
2  Devendra   25

In [ ]:
tbl1 = pd.Series(df['age'])
tbl2 = pd.Series(df['gender'])
data = {
    "age" : tbl1,
    "gender" : tbl2
}

dataframe = pd.DataFrame(data)
dataframe

    Name     Age
0     60    Male
1     27    Male
2     42    Male
3     31  Female
4     65  Female
..   ...     ...
95    12  Female
96    51  Female
97    20  Female
98     5  Female
99    10  Female

[100 rows x 2 columns]

In [ ]:
os.getcwd()
# current wroking directry = cwd

'c:\\Users\\Syed\\Desktop\\ADV Py'

In [19]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
## Importing Dataset
df = pd.read_csv('data\covid_toy.csv')
df.head()

# .head() is used to give 5 starting values by default
# but you can get wanted no. of output

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.tail()



# tail is used to give u 5 last record

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [ ]:
df.info()

# .info is used to give info about the dataset

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    str
 2   fever      90 non-null     float64
 3   cough      100 non-null    str
 4   city       100 non-null    str
 5   has_covid  100 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 4.8 KB

In [ ]:
df.describe()

# .describe is used to give u statistical info like count,mean etc

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [ ]:
df.isnull()

# isnull give u the boolian result for the null value

      age  gender  fever  cough   city  has_covid
0   False   False  False  False  False      False
1   False   False  False  False  False      False
2   False   False  False  False  False      False
3   False   False  False  False  False      False
4   False   False  False  False  False      False
..    ...     ...    ...    ...    ...        ...
95  False   False  False  False  False      False
96  False   False  False  False  False      False
97  False   False  False  False  False      False
98  False   False  False  False  False      False
99  False   False  False  False  False      False

[100 rows x 6 columns]

In [ ]:
df.isnull().sum()
# .sum() is used to give u the null value in no. like how many null value u have in which column

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
## .loc and .iloc
df.loc[3:6,['age','fever']]

# loc is define location of dataframe 
# df.loc[row range,[column name]]

   age  fever
3   31   98.0
4   65  101.0
5   84    NaN
6   14  101.0

In [ ]:
df.iloc[3:6,0:5]
# iloc provide the location on the basis od index no.
# it have 2 formets 
#  1st. df.iloc[row index range,column index range]
#  2nd. df.iloc[row index range,[column index no.]]

   age  gender  fever cough       city
3   31  Female   98.0  Mild    Kolkata
4   65  Female  101.0  Mild     Mumbai
5   84  Female    NaN  Mild  Bangalore

In [ ]:
df.iloc[3:6,[1,2,5]]

   gender  fever has_covid
3  Female   98.0        No
4  Female  101.0        No
5  Female    NaN       Yes

In [30]:
df.iloc[3:6,-1]

3     No
4     No
5    Yes
Name: has_covid, dtype: str

In [39]:
df['city'].value_counts()
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [40]:
print(df)

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
df.columns

# .column is used to get the list of column

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='str')

In [23]:
## Filling the missing vaues
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [27]:
df = pd.read_csv('data\covid_toy.csv')

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Syed\AppData\Local\Temp\ipykernel_9024\3918093160.py:1: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv('data\covid_toy.csv')

In [ ]:
fever_mean = df['fever'].mean()
df.fillna(fever_mean, inplace=False)

age_mean = df['age'].mean()
df.fillna(age_mean, inplace=False)

# .fillna fills the null value with the element u give

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [29]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [45]:
df['fever'] = df['fever'].fillna((0))
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
## Dropping the missing values
df = pd.read_csv('data\covid_toy.csv')

df = df.dropna()
df.info()

# dropna delete the row in which null value is presented

<class 'pandas.DataFrame'>
Index: 90 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        90 non-null     int64
 1   gender     90 non-null     str
 2   fever      90 non-null     float64
 3   cough      90 non-null     str
 4   city       90 non-null     str
 5   has_covid  90 non-null     str
dtypes: float64(1), int64(1), str(4)
memory usage: 4.9 KB

<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:2: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Syed\AppData\Local\Temp\ipykernel_9024\677643796.py:2: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv('data\covid_toy.csv')

In [ ]:
## Dropping a specific column
df = pd.read_csv('data\covid_toy.csv')

df = df.drop(columns=('has_covid'))
df
# drop delete the desirable column

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [ ]:
df = pd.read_csv('data\covid_toy.csv')

#x = df.drop(columns= ['has_covid', 'age'])
#y = df['has_covid']

a= df.drop(columns=['age','has_covid'])
b= df['has_covid']
print(a)
print(b)

    gender  fever   cough       city
0     Male  103.0    Mild    Kolkata
1     Male  100.0    Mild      Delhi
2     Male  101.0    Mild      Delhi
3   Female   98.0    Mild    Kolkata
4   Female  101.0    Mild     Mumbai
..     ...    ...     ...        ...
95  Female  104.0    Mild  Bangalore
96  Female  101.0  Strong    Kolkata
97  Female  101.0    Mild  Bangalore
98  Female   98.0  Strong     Mumbai
99  Female   98.0  Strong    Kolkata

[100 rows x 4 columns]
0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: str

In [38]:
x

    gender  fever   cough       city
0     Male  103.0    Mild    Kolkata
1     Male  100.0    Mild      Delhi
2     Male  101.0    Mild      Delhi
3   Female   98.0    Mild    Kolkata
4   Female  101.0    Mild     Mumbai
..     ...    ...     ...        ...
95  Female  104.0    Mild  Bangalore
96  Female  101.0  Strong    Kolkata
97  Female  101.0    Mild  Bangalore
98  Female   98.0  Strong     Mumbai
99  Female   98.0  Strong    Kolkata

[100 rows x 4 columns]

In [35]:
y

0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: str

In [ ]:
df = pd.read_csv('data\covid_toy.csv')

df = df.rename(columns= {"has_covid" : "isCovid"})
df.head()

df = df.rename(columns={'age':'your_age'})
df

# rename changes the name of the column heading

    your_age  gender  fever   cough       city isCovid
0         60    Male  103.0    Mild    Kolkata      No
1         27    Male  100.0    Mild      Delhi     Yes
2         42    Male  101.0    Mild      Delhi      No
3         31  Female   98.0    Mild    Kolkata      No
4         65  Female  101.0    Mild     Mumbai      No
..       ...     ...    ...     ...        ...     ...
95        12  Female  104.0    Mild  Bangalore      No
96        51  Female  101.0  Strong    Kolkata     Yes
97        20  Female  101.0    Mild  Bangalore      No
98         5  Female   98.0  Strong     Mumbai      No
99        10  Female   98.0  Strong    Kolkata     Yes

[100 rows x 6 columns]

In [67]:
df = pd.read_csv('data\covid_toy.csv')

df['age'] = df['age'] + 10
df.head()

df['fever'] = df['fever'] +5
df
# it added or subtract in anything but it must be numaric

    age  gender  fever   cough       city has_covid
0    70    Male  108.0    Mild    Kolkata        No
1    37    Male  105.0    Mild      Delhi       Yes
2    52    Male  106.0    Mild      Delhi        No
3    41  Female  103.0    Mild    Kolkata        No
4    75  Female  106.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   22  Female  109.0    Mild  Bangalore        No
96   61  Female  106.0  Strong    Kolkata       Yes
97   30  Female  106.0    Mild  Bangalore        No
98   15  Female  103.0  Strong     Mumbai        No
99   20  Female  103.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [42]:
df[['age', 'city']].head()

   age     city
0   60  Kolkata
1   27    Delhi
2   42    Delhi
3   31  Kolkata
4   65   Mumbai

In [ ]:
df.sample(10)

# sample give us any rendom no. from your dataframe

    age  gender  fever   cough       city isCovid  Age
28   16    Male  104.0    Mild    Kolkata      No   26
88    5  Female  100.0    Mild    Kolkata      No   15
17   40  Female   98.0  Strong      Delhi      No   50
90   59  Female   99.0  Strong      Delhi      No   69
33   26  Female   98.0    Mild    Kolkata      No   36
76   80    Male  100.0    Mild  Bangalore     Yes   90
98    5  Female   98.0  Strong     Mumbai      No   15
60   24  Female  102.0  Strong  Bangalore     Yes   34
7    20  Female    NaN  Strong     Mumbai     Yes   30
0    60    Male  103.0    Mild    Kolkata      No   70

In [ ]:
df.dtypes

# it tells u the datatype of your each column

age          int64
gender         str
fever      float64
cough          str
city           str
isCovid        str
Age          int64
dtype: object